version: "3.8"

services:
  rabbitmq:
    image: docker.io/rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

  db:
    image: docker.io/library/postgres:16-alpine
    container_name: bombdb
    restart: unless-stopped
    ports:
      - "9876:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - bombdb_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  website:
    image: ghcr.io/n3moahead/bombahead/website:latest
    container_name: bombahead
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DBURI: ${DBURI}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      NEXT_AUTH_URL: ${NEXT_AUTH_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      IS_PRODUCTION: ${IS_PRODUCTION}
      CSRF_AUTH_KEY: ${CSRF_AUTH_KEY}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_MATCH_QUEUE: ${RABBITMQ_MATCH_QUEUE}
      RABBITMQ_RESULT_QUEUE: ${RABBITMQ_RESULT_QUEUE}

  matchmaker:
    image: ghcr.io/n3moahead/bombahead/matchmaker:latest
    container_name: matchmaker
    restart: unless-stopped
    environment:
      DBURI: ${DBURI}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      NEXT_AUTH_URL: ${NEXT_AUTH_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      IS_PRODUCTION: ${IS_PRODUCTION}
      CSRF_AUTH_KEY: ${CSRF_AUTH_KEY}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_MATCH_QUEUE: ${RABBITMQ_MATCH_QUEUE}
      RABBITMQ_RESULT_QUEUE: ${RABBITMQ_RESULT_QUEUE}

  matchrunner:
    image: ghcr.io/n3moahead/bombahead/match-runner:latest
    container_name: matchrunner
    restart: unless-stopped
    environment:
      CONTAINER_HOST: ${CONTAINER_HOST}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_MATCH_QUEUE: ${RABBITMQ_MATCH_QUEUE}
      RABBITMQ_RESULT_QUEUE: ${RABBITMQ_RESULT_QUEUE}
    volumes:
      - /run/user/1000/podman/podman.sock:/run/podman/podman.sock

volumes:
  rabbitmq_data:
  bombdb_postgres_data:
